// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/hcore/hcore_service.proto

package hcore

import (
	hcommon "github.com/twilgate/inhive-core/v2/hcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v2_hcore_hcore_service_proto protoreflect.FileDescriptor

const file_v2_hcore_hcore_service_proto_rawDesc = "" +
	"\n" +
	"\x1cv2/hcore/hcore_service.proto\x12\x05hcore\x1a\x17v2/hcommon/common.proto\x1a\x14v2/hcore/hcore.proto2\xe3\t\n" +
	"\x04Core\x125\n" +
	"\x05Start\x12\x13.hcore.StartRequest\x1a\x17.hcore.CoreInfoResponse\x12=\n" +
	"\x10CoreInfoListener\x12\x0e.hcommon.Empty\x1a\x17.hcore.CoreInfoResponse0\x01\x122\n" +
	"\rGetSystemInfo\x12\x0e.hcommon.Empty\x1a\x11.hcore.SystemInfo\x12/\n" +
	"\x05Setup\x12\x13.hcore.SetupRequest\x1a\x11.hcommon.Response\x122\n" +
	"\x05Parse\x12\x13.hcore.ParseRequest\x1a\x14.hcore.ParseResponse\x12M\n" +
	"\x0eBootstrapFetch\x12\x1c.hcore.BootstrapFetchRequest\x1a\x1d.hcore.BootstrapFetchResponse\x12J\n" +
	"\rUrlTestConfig\x12\x1b.hcore.UrlTestConfigRequest\x1a\x1c.hcore.UrlTestConfigResponse\x12S\n" +
	"\x14ChangeInhiveSettings\x12\".hcore.ChangeInhiveSettingsRequest\x1a\x17.hcore.CoreInfoResponse\x12/\n" +
	"\x04Stop\x12\x0e.hcommon.Empty\x1a\x17.hcore.CoreInfoResponse\x12A\n" +
	"\x0eSelectOutbound\x12\x1c.hcore.SelectOutboundRequest\x1a\x11.hcommon.Response\x12D\n" +
	"\vAddOutbound\x12\x19.hcore.AddOutboundRequest\x1a\x1a.hcore.AddOutboundResponse\x12A\n" +
	"\x0eRemoveOutbound\x12\x1c.hcore.RemoveOutboundRequest\x1a\x11.hcommon.Response\x123\n" +
	"\aUrlTest\x12\x15.hcore.UrlTestRequest\x1a\x11.hcommon.Response\x122\n" +
	"\rUrlTestActive\x12\x0e.hcommon.Empty\x1a\x11.hcommon.Response\x12>\n" +
	"\tSpeedTest\x12\x17.hcore.SpeedTestRequest\x1a\x18.hcore.SpeedTestResponse\x12U\n" +
	"\x12GenerateWarpConfig\x12 .hcore.GenerateWarpConfigRequest\x1a\x1d.hcore.WarpGenerationResponse\x125\n" +
	"\vLogListener\x12\x11.hcore.LogRequest\x1a\x11.hcore.LogMessage0\x01\x12,\n" +
	"\x05Close\x12\x13.hcore.CloseRequest\x1a\x0e.hcommon.Empty\x129\n" +
	"\n" +
	"SwitchMode\x12\x18.hcore.SwitchModeRequest\x1a\x11.hcommon.Response\x12?\n" +
	"\x11ModeStateListener\x12\x0e.hcommon.Empty\x1a\x18.hcore.ModeStateResponse0\x01BH\n" +
	"\x1ccom.inhive.core.api.v2.hcoreZ(github.com/twilgate/inhive-core/v2/hcoreb\x06proto3"

var file_v2_hcore_hcore_service_proto_goTypes = []any{
	(*StartRequest)(nil),                // 0: hcore.StartRequest
	(*hcommon.Empty)(nil),               // 1: hcommon.Empty
	(*SetupRequest)(nil),                // 2: hcore.SetupRequest
	(*ParseRequest)(nil),                // 3: hcore.ParseRequest
	(*BootstrapFetchRequest)(nil),       // 4: hcore.BootstrapFetchRequest
	(*UrlTestConfigRequest)(nil),        // 5: hcore.UrlTestConfigRequest
	(*ChangeInhiveSettingsRequest)(nil), // 6: hcore.ChangeInhiveSettingsRequest
	(*SelectOutboundRequest)(nil),       // 7: hcore.SelectOutboundRequest
	(*AddOutboundRequest)(nil),          // 8: hcore.AddOutboundRequest
	(*RemoveOutboundRequest)(nil),       // 9: hcore.RemoveOutboundRequest
	(*UrlTestRequest)(nil),              // 10: hcore.UrlTestRequest
	(*SpeedTestRequest)(nil),            // 11: hcore.SpeedTestRequest
	(*GenerateWarpConfigRequest)(nil),   // 12: hcore.GenerateWarpConfigRequest
	(*LogRequest)(nil),                  // 13: hcore.LogRequest
	(*CloseRequest)(nil),                // 14: hcore.CloseRequest
	(*SwitchModeRequest)(nil),           // 15: hcore.SwitchModeRequest
	(*CoreInfoResponse)(nil),            // 16: hcore.CoreInfoResponse
	(*SystemInfo)(nil),                  // 17: hcore.SystemInfo
	(*hcommon.Response)(nil),            // 18: hcommon.Response
	(*ParseResponse)(nil),               // 19: hcore.ParseResponse
	(*BootstrapFetchResponse)(nil),      // 20: hcore.BootstrapFetchResponse
	(*UrlTestConfigResponse)(nil),       // 21: hcore.UrlTestConfigResponse
	(*AddOutboundResponse)(nil),         // 22: hcore.AddOutboundResponse
	(*SpeedTestResponse)(nil),           // 23: hcore.SpeedTestResponse
	(*WarpGenerationResponse)(nil),      // 24: hcore.WarpGenerationResponse
	(*LogMessage)(nil),                  // 25: hcore.LogMessage
	(*ModeStateResponse)(nil),           // 26: hcore.ModeStateResponse
}
var file_v2_hcore_hcore_service_proto_depIdxs = []int32{
	0,  // 0: hcore.Core.Start:input_type -> hcore.StartRequest
	1,  // 1: hcore.Core.CoreInfoListener:input_type -> hcommon.Empty
	1,  // 2: hcore.Core.GetSystemInfo:input_type -> hcommon.Empty
	2,  // 3: hcore.Core.Setup:input_type -> hcore.SetupRequest
	3,  // 4: hcore.Core.Parse:input_type -> hcore.ParseRequest
	4,  // 5: hcore.Core.BootstrapFetch:input_type -> hcore.BootstrapFetchRequest
	5,  // 6: hcore.Core.UrlTestConfig:input_type -> hcore.UrlTestConfigRequest
	6,  // 7: hcore.Core.ChangeInhiveSettings:input_type -> hcore.ChangeInhiveSettingsRequest
	1,  // 8: hcore.Core.Stop:input_type -> hcommon.Empty
	7,  // 9: hcore.Core.SelectOutbound:input_type -> hcore.SelectOutboundRequest
	8,  // 10: hcore.Core.AddOutbound:input_type -> hcore.AddOutboundRequest
	9,  // 11: hcore.Core.RemoveOutbound:input_type -> hcore.RemoveOutboundRequest
	10, // 12: hcore.Core.UrlTest:input_type -> hcore.UrlTestRequest
	1,  // 13: hcore.Core.UrlTestActive:input_type -> hcommon.Empty
	11, // 14: hcore.Core.SpeedTest:input_type -> hcore.SpeedTestRequest
	12, // 15: hcore.Core.GenerateWarpConfig:input_type -> hcore.GenerateWarpConfigRequest
	13, // 16: hcore.Core.LogListener:input_type -> hcore.LogRequest
	14, // 17: hcore.Core.Close:input_type -> hcore.CloseRequest
	15, // 18: hcore.Core.SwitchMode:input_type -> hcore.SwitchModeRequest
	1,  // 19: hcore.Core.ModeStateListener:input_type -> hcommon.Empty
	16, // 20: hcore.Core.Start:output_type -> hcore.CoreInfoResponse
	16, // 21: hcore.Core.CoreInfoListener:output_type -> hcore.CoreInfoResponse
	17, // 22: hcore.Core.GetSystemInfo:output_type -> hcore.SystemInfo
	18, // 23: hcore.Core.Setup:output_type -> hcommon.Response
	19, // 24: hcore.Core.Parse:output_type -> hcore.ParseResponse
	20, // 25: hcore.Core.BootstrapFetch:output_type -> hcore.BootstrapFetchResponse
	21, // 26: hcore.Core.UrlTestConfig:output_type -> hcore.UrlTestConfigResponse
	16, // 27: hcore.Core.ChangeInhiveSettings:output_type -> hcore.CoreInfoResponse
	16, // 28: hcore.Core.Stop:output_type -> hcore.CoreInfoResponse
	18, // 29: hcore.Core.SelectOutbound:output_type -> hcommon.Response
	22, // 30: hcore.Core.AddOutbound:output_type -> hcore.AddOutboundResponse
	18, // 31: hcore.Core.RemoveOutbound:output_type -> hcommon.Response
	18, // 32: hcore.Core.UrlTest:output_type -> hcommon.Response
	18, // 33: hcore.Core.UrlTestActive:output_type -> hcommon.Response
	23, // 34: hcore.Core.SpeedTest:output_type -> hcore.SpeedTestResponse
	24, // 35: hcore.Core.GenerateWarpConfig:output_type -> hcore.WarpGenerationResponse
	25, // 36: hcore.Core.LogListener:output_type -> hcore.LogMessage
	1,  // 37: hcore.Core.Close:output_type -> hcommon.Empty
	18, // 38: hcore.Core.SwitchMode:output_type -> hcommon.Response
	26, // 39: hcore.Core.ModeStateListener:output_type -> hcore.ModeStateResponse
	20, // [20:40] is the sub-list for method output_type
	0,  // [0:20] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v2_hcore_hcore_service_proto_init() }
func file_v2_hcore_hcore_service_proto_init() {
	if File_v2_hcore_hcore_service_proto != nil {
		return
	}
	file_v2_hcore_hcore_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_hcore_hcore_service_proto_rawDesc), len(file_v2_hcore_hcore_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_hcore_hcore_service_proto_goTypes,
		DependencyIndexes: file_v2_hcore_hcore_service_proto_depIdxs,
	}.Build()
	File_v2_hcore_hcore_service_proto = out.File
	file_v2_hcore_hcore_service_proto_goTypes = nil
	file_v2_hcore_hcore_service_proto_depIdxs = nil
}
