package ray2sing_test

// awg_conf_test.go — acceptance guard for the wg-quick / AmneziaWG `.conf`
// branch of ConvertToShareLinks (user report 2026-08: generators hand out
// .conf files, pasting/importing them said "не распознано" because the
// multi-line INI fell through to the share-link text path and got shredded
// into lines by the app).
//
// Same bar as convert_sharelinks_test.go: the record must be the canonical
// wg:// / awg:// URI, and feeding it back through the full pipeline must
// rebuild the same semantic fields ("semantically == the conf", not "it
// parsed").

import (
	"strings"
	"testing"

	"github.com/twilgate/xray2sing/ray2sing"
)

const awgConfBody = `[Interface]
PrivateKey = SFRcP2pft4dVXLKC9d0adCLJXFsQ+eLOX/DGYcYaCEE=
Address = 10.8.1.2/32
DNS = 1.1.1.1
Jc = 7
Jmin = 50
Jmax = 1000
S1 = 68
S2 = 149
H1 = 1004746675
H2 = 1157755290
H3 = 1273046607
H4 = 2137162994

[Peer]
PublicKey = xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=
PresharedKey = CPQ9IxTCWXfyMLZmn9dV1zwlsPvvg8r0jmnPKAA0zEo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.12.34:51820
PersistentKeepalive = 25
`

func TestConvert_AWGConf_CanonicalURI(t *testing.T) {
	rec := oneRecord(t, awgConfBody)
	if !strings.HasPrefix(rec, "awg://") {
		t.Fatalf("want an awg:// canonical URI (Amnezia obfs present), got: %s", rec)
	}
	for _, key := range []string{"jc=7", "jmin=50", "jmax=1000", "s1=68", "s2=149", "h1=1004746675", "h4=2137162994", "presharedkey=", "keepalive=25"} {
		if !strings.Contains(rec, key) {
			t.Errorf("URI missing %q: %s", key, rec)
		}
	}

	ep := firstEndpoint(t, rec)
	if ep["type"] != "awg" {
		t.Fatalf("endpoint type = %v, want awg", ep["type"])
	}
	if ep["private_key"] != "SFRcP2pft4dVXLKC9d0adCLJXFsQ+eLOX/DGYcYaCEE=" {
		t.Errorf("private_key = %v (base64 with '+'/'/' must survive verbatim)", ep["private_key"])
	}
	if a := asStrings(ep["address"]); !eqStrings(a, []string{"10.8.1.2/32"}) {
		t.Errorf("address = %v, want [10.8.1.2/32]", ep["address"])
	}
	peers, _ := ep["peers"].([]any)
	if len(peers) != 1 {
		t.Fatalf("peers = %v, want exactly 1", ep["peers"])
	}
	p := peers[0].(map[string]any)
	if p["address"] != "146.70.12.34" || p["port"] != float64(51820) {
		t.Errorf("peer endpoint = %v:%v, want 146.70.12.34:51820", p["address"], p["port"])
	}
	// The comma list "0.0.0.0/0, ::/0" (typical Amnezia output) used to hard-fail
	// the whole conf via a single ParsePrefix.
	if !eqStrings(asStrings(p["allowed_ips"]), []string{"0.0.0.0/0", "::/0"}) {
		t.Errorf("allowed_ips = %v, want [0.0.0.0/0 ::/0]", p["allowed_ips"])
	}
}

// Plain WireGuard conf (no Jc/S/H obfs params) must emit wireguard://, not awg://.
func TestConvert_PlainWGConf_CanonicalURI(t *testing.T) {
	conf := `[Interface]
PrivateKey = kL9x+Yz3/AbC7dEf+GhI2jKl/MnOp4=
Address = 10.13.13.2/32

[Peer]
PublicKey = Pub+Key/With+Slash2jKlMnOpQrStUv=
AllowedIPs = 0.0.0.0/0
Endpoint = vpn.example.com:51820
`
	rec := oneRecord(t, conf)
	if !strings.HasPrefix(rec, "wireguard://") {
		t.Fatalf("want a wireguard:// canonical URI, got: %s", rec)
	}
	ep := firstEndpoint(t, rec)
	if ep["type"] != "wireguard" {
		t.Fatalf("endpoint type = %v, want wireguard", ep["type"])
	}
}

// Generators prepend comments (# and ;), blank lines and a UTF-8 BOM; wg(8)
// section names are case-insensitive. None of that may break detection.
func TestConvert_AWGConf_ToleratesJunkAndCase(t *testing.T) {
	conf := "\uFEFF" + `
# Generated by AmneziaVPN
; keep this file secret

[interface]
PrivateKey = SFRcP2pft4dVXLKC9d0adCLJXFsQ+eLOX/DGYcYaCEE=
Address = 10.8.1.2/32
Jc = 7

[peer]
PublicKey = xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=
Endpoint = 146.70.12.34:51820
`
	rec := oneRecord(t, conf)
	if !strings.HasPrefix(rec, "awg://") {
		t.Fatalf("want an awg:// URI despite BOM/comments/lowercase, got: %s", rec)
	}
}

// A file concatenating several tunnels yields one record per [Interface] block.
func TestConvert_AWGConf_MultipleTunnels(t *testing.T) {
	two := awgConfBody + "\n" + `[Interface]
PrivateKey = kL9x+Yz3/AbC7dEf+GhI2jKl/MnOp4=
Address = 10.13.13.2/32

[Peer]
PublicKey = Pub+Key/With+Slash2jKlMnOpQrStUv=
Endpoint = vpn.example.com:51820
`
	recs := records(t, two)
	if len(recs) != 2 {
		t.Fatalf("want 2 records, got %d: %v", len(recs), recs)
	}
	if !strings.HasPrefix(recs[0], "awg://") || !strings.HasPrefix(recs[1], "wireguard://") {
		t.Errorf("want [awg://…, wireguard://…], got: %v", recs)
	}
}

// A conf with several [Peer] blocks has no single-URI form → endpoint JSON
// fallback (universal-client: the server is never lost).
func TestConvert_AWGConf_MultiPeerFallback(t *testing.T) {
	conf := `[Interface]
PrivateKey = kL9x+Yz3/AbC7dEf+GhI2jKl/MnOp4=
Address = 10.13.13.2/32

[Peer]
PublicKey = cHViMQ==
Endpoint = a.example.com:51820

[Peer]
PublicKey = cHViMg==
Endpoint = b.example.com:51821
`
	rec := oneRecord(t, conf)
	if strings.HasPrefix(rec, "wireguard://") || strings.HasPrefix(rec, "awg://") {
		t.Fatalf("multi-peer conf must degrade to JSON, not a lossy single-peer URI: %s", rec)
	}
	if !strings.HasPrefix(rec, "{") || !strings.Contains(rec, `"type":"wireguard"`) {
		t.Errorf("fallback must be the preserved endpoint JSON, got: %s", rec)
	}
}

// A detected conf whose every tunnel is broken must hard-error like the other
// branches — not fall through to the share-link path and shred the INI.
func TestConvert_AWGConf_BrokenIsHardError(t *testing.T) {
	_, err := ray2sing.ConvertToShareLinks("[Interface]\nAddress = 10.0.0.2/32\n")
	if err == nil {
		t.Fatal("want an error for a conf without PrivateKey/peer, got nil")
	}
}
